secret_key: "replace_with_your_secret_key"
admin_password: "replace_with_admin_password"
two_point_cutoff: 0.1 # Derivation from the correct answer to get 2 points
one_point_cutoff: 0.2 # Derivation from the correct answer to get 1 point
teams:
    - Team 1
    - Team 2
    - Team 3
    # Add more teams as needed
